name: Build, Push, and Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t flask-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag flask-app:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}

      - name: Make generate-metadata.sh executable
        run: chmod +x ./generate-metadata.sh

      - name: Generate Docker image metadata
        run: ./generate-metadata.sh
        env:
            GITHUB_SHA: ${{ github.sha }}
  
      - name: Upload Docker image metadata
        uses: actions/upload-artifact@v3
        with:
            name: docker-image-metadata
            path: ./docker-image-metadata.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install kubectl
        run: |
          gcloud components install kubectl

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/flask-app flask-app=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          kubectl rollout status deployment/flask-app
