name: Maven build

on:
    workflow_call:
        inputs:
            java-version:
                required: false
                type: string
                default: '11'
                description: "java version for build"
            maven-goals:
                required: false
                type: string
                default: 'clean install'
                description: "maven goals to execute"
            maven-settings-file:
                required: false
                type: string
                description: "path to a custom maven settings.xml"
            maven-options:
                required: false
                type: string
                description: "additional maven options"
        secrets:
            maven-username:
                required: false
                description: "Username for Maven Central or other private repositories"
            maven-password:
                required: false
                description: "Password for Maven Central or other private repositories"
        outputs:
            build-status:
                description: "Statud of the maven build"
                value: ${{ jobs.build.outcome }}

jobs:
    build-maven:
        runs-on: ubuntu-latest

        steps:
            - name: CHeckout code
              uses: actions/checkout@v4

            - name: Set up JDK ${{ inputs.java-version }}
              uses: actions/setup-java@v3
              with:
                java-version: ${{ inputs.java-version }}
                distribution: 'temurin'
                # settings-file: ${{ inputs.mave-settings-file }}

            # - name: Configure Maven credentials (if provided)
            #   if: ${{ secrets.maven-central-username != '' && secrets.maven-central-password != '' }}
            #   run: |
            #       mkdir -p ~/.m2
            #       cat <<EOF > ~/.m2/settings.xml
            #       <settings>
            #         <servers>
            #           <server>
            #             <id>maven-central</id>
            #             <username>${{ secrets.maven-central-username }}</username>
            #             <password>${{ secrets.maven-central-password }}</password>
            #           </server>
            #         </servers>
            #       </settings>
            #       EOF
            - name: Build Maven
              id: maven-build-step
              run: mvn ${{ inputs.maven-goals }} ${{ inputs.maven-options}}

            