name: Build npm

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18'
        description: "Node.js version for build"
      npm-install-options:
        required: false
        type: string
        default: 'npm install'
        description: "additional npm install options"
      npm-build-options:
        required: false
        type: string
        default: 'npm run build'
        description: "additional npm build options"
      npm-test-options:
        required: false
        type: string
        default: 'npm test'
        description: "additional npm test options"

jobs:
    build-npm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js ${{ inputs.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}

            - name: Install npm dependencies
              run: ${{ inputs.npm-install-options }}

            - name: Build npm project
              run: ${{ inputs.npm-build-options }}

            - name: Run tests
              run: ${{ inputs.npm-test-options }}