name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build Docker and Push to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Get the latest image digest
        id: image-digest
        run: |
          IMAGE_DIGEST=$(ghcr.io/${{ github.repository }} | jq -r '.[0].digest')
          echo "::set-output name=digest::${IMAGE_DIGEST}"

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

      - name: Update deployment image
        run: |
          kubectl set image deployment/flask-app flask-app=ghcr.io/${{ github.repository }}@${{ steps.image-digest.outputs.digest }}

      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/flask-app
