name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build and Push Docker image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with GCP
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Download Docker image metadata
        uses: actions/download-artifact@v3
        with:
          name: docker-image-metadata
          path: ./metadata

      - name: Deploy to GKE
        run: |
          IMAGE_TAG=$(cat ./metadata/docker-image-metadata.json | jq -r '.tag')
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}
          kubectl set image deployment/flask-app flask-app=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$IMAGE_TAG
