name: Main build workflow

on:
   workflow_call:
        inputs:
            build-type:
                description: 'Type of build to perform'
                required: true
                type: string
                
jobs:
    choose-build:
        runs-on: ubuntu-latest

        steps:
            
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Choose build type
              id: build-type
              run: |
                echo "Build type is ${{ inputs.build-type }}"
                if [ "${{ inputs.build-type }}" == "docker" ]; then
                    echo "Running Docker build"
                    echo "build-type=docker" >> $GITHUB_OUTPUT
                elif [ "${{ inputs.build-type }}" == "maven" ]; then
                    echo "Running Maven build"
                    echo "build-type=maven" >> $GITHUB_OUTPUT
                elif [ "${{ inputs.build-type }}" == "npm" ]; then
                    echo "Running NPM build"
                    echo "build-type=npm" >> $GITHUB_OUTPUT
                else
                    echo "Unknown build type: ${{ inputs.build-type }}"
                    exit 1
                fi

            - name: Run Docker build
              if: ${{ inputs.build-type }} == 'docker'
              uses: ./.github/workflows/build-docker.yml
              with:
                dockerfile: ${{ github.workspace }}/Dockerfile
                context: ${{ github.workspace }}
                image_tags: ghcr.io/${{ github.repository }}:latest
                registry: ghcr.io
                push: true

            - name: Run Maven build
              if: ${{ inputs.build-type }} == 'maven'
              uses: ./.github/workflows/build-maven.yml
              with:
                java-version: '17'
                maven-goals: 'clean package'

            - name: Run NPM build
              if: ${{ inputs.build-type }} == 'npm'
              uses: ./.github/workflows/build-npm.yml

