name: Main build workflow

on:
   workflow_call:
        inputs:
            build-type:
                description: 'Type of build to perform'
                required: true
                type: string
                
jobs:
    choose-build:
        runs-on: ubuntu-latest

        steps:
            
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Choose build type
              id: build-type
              run: |
                echo "Build type is ${{ inputs.build-type }}"
                if [ "${{ inputs.build-type }}" == "docker" ]; then
                    echo "Running Docker build"
                    echo "$build-type=docker" >> $GITHUB_ENV
                elif [ "${{ inputs.build-type }}" == "maven" ]; then
                    echo "Running Maven build"
                    echo "$build-type=maven" >> $GITHUB_ENV
                elif [ "${{ inputs.build-type }}" == "npm" ]; then
                    echo "Running NPM build"
                    echo "$build-type=npm" >> $GITHUB_ENV
                else
                    echo "Unknown build type: ${{ inputs.build-type }}"
                    exit 1
                fi
           
    docker-build-job:
        if: ${{ inputs.build-type  == 'docker' }}
        uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-docker.yml@main
        with:
          dockerfile: ${{ github.workspace }}/Dockerfile
          image_tags: ghcr.io/${{ github.repository }}:latest
          registry: ghcr.io
          push: true

    maven-build-job:
        if: ${{ inputs.build-type == 'maven' }}
        uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-maven.yml@main
        with:
          java-version: '17'
          maven-goals: 'clean package'

    npm-build-job:          
        if: ${{ inputs.build-type  == 'npm' }}
        uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-npm.yml@main
        with:
            node-version: '18'
      
    

