name: Run Flask App

on:
    push:
        branches:
        - main

jobs:
    run-flask-app:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
                python-version: 3.8

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        - name: Run Flask app
          env:
            FLASK_APP: hello.py
            FLASK_ENV: development
          run: |
            flask run --host=0.0.0.0 --port=5000 &
            sleep 10
        
