name: SonarQube Scan

on:
  push:
    branches:
      - main


jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            -Dsonar.projectKey="iiakovleva-l_playground" \
            -Dsonar.sources=. \
            -Dsonar.host.url="https://sonarcloud.io/project/overview?id=iiakovleva-l_playground" \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Upload sonar report
        uses: actions/upload-artifact@v3
        with:
          name: sonar-report
          path: .scannerwork/report-task.txt
